#!/bin/bash

set -xe

# repo downloads

echo "Adding Unity repo"
wget -qO - https://hub.unity3d.com/linux/keys/public | gpg --dearmor | sudo tee /usr/share/keyrings/Unity_Technologies_ApS.gpg > /dev/null
sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/Unity_Technologies_ApS.gpg] https://hub.unity3d.com/linux/repos/deb stable main" > /etc/apt/sources.list.d/unityhub.list'

# repo installs

echo "Installing repos"
sudo apt-get update
sudo apt-get install -y dotnet-sdk-6.0
sudo apt-get install -y unityhub

# vpm install

if ! command -v vpm &> /dev/null
then
    dotnet tool install --global vrchat.vpm.cli
else
    echo "vpm is already installed"
fi

# vpm settings configuration

current_dir=$(dirname "$(realpath "$0")")
unityhub_dir="$current_dir/unityhub"
settings_file="$HOME/.local/share/VRChatCreatorCompanion/settings.json"

jq --arg dir "$unityhub_dir" '.pathToUnityHub = $dir' "$settings_file" > "$settings_file.tmp" && mv "$settings_file.tmp" "$settings_file"
# vpm commands

yes | vpm install unity

